services:
  ai-service:
    container_name: detect_ai_inference
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "${PORT_INFERENCE}:50051"
      - "${PORT_INFERENCE_METRICS}:8333"
    networks:
      - detectai_net
    environment:
      - PYTHONUNBUFFERED=1
      - GRPC_PORT=50051
      - AI_SERVICE_API_KEY=${AI_SERVICE_API_KEY}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

networks:
  detectai_net:
    name: ${detect_ai_network}
    external: true