name: detect_ai_web

include:
  - path: ./infra/docker/postgres.yml
  - path: ./infra/docker/redis.yml

networks:
  detectai_net:
    external: true

services:
  frontend:
    container_name: detect_ai_frontend
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0
      - REDIS_SENTINELS=detect_ai_redis_sentinel_1:26379,detect_ai_redis_sentinel_2:26379,detect_ai_redis_sentinel_3:26379
      - REDIS_MASTER_NAME=mymaster
      - REDIS_USAGE_URL=redis://:worker_password@detect_ai_redis_ratelimit:6379
    networks:
      - detectai_net
    depends_on:
      redis-master:
        condition: service_healthy
      postgres-primary:
        condition: service_healthy