services:
  frontend:
    container_name: detect_ai_frontend
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - NODE_ENV=${NODE_ENV}
      - HOSTNAME=0.0.0.0
      - REDIS_SENTINELS=detect_ai_redis_sentinel_1:26379,detect_ai_redis_sentinel_2:26379,detect_ai_redis_sentinel_3:26379
      - REDIS_MASTER_NAME=mymaster
      - USE_REDIS_CLUSTER=true
      - REDIS_USAGE_URL=${REDIS_USAGE_URL}
      - FILE_EXTRACTOR_API_URL=${FILE_EXTRACTOR_API_URL}
      - AI_SERVICE_URL=${AI_SERVICE_URL}
      - CHAT_SERVICE_URL=${CHAT_SERVICE_URL}
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_URL_REPLICA=${DATABASE_URL_REPLICA}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - PAYMENT_GATEWAY_URL=${PAYMENT_GATEWAY_URL}
    ports:
      - "${PORT_FRONTEND}:3000"
    networks:
      - detectai_net
    depends_on:
      postgres-primary:
        condition: service_healthy
      redis-master:
        condition: service_healthy
      document-parser:
        condition: service_started
      ai-service:
        condition: service_started
      payment-gateway:
        condition: service_started
      chat-service:
        condition: service_started

networks:
  detectai_net:
    name: ${detect_ai_network}
    external: true