export const HERO_TEXT = {
  badge: "Introducing Detect AI",
  titleStart: "Detect your text",
  titleEnd: "in Seconds!",
  description: "Provide your text, and our model will predict its classification. Fast and efficient predictions in seconds.",
  cta: "Get started!"
}

export const VISUALIZER_TEXT = "This text is being analyzed by our advanced AI detection algorithm to determine if it was written by a human or generated by AI. Our model processes patterns, structures, and linguistic features to provide accurate classification in seconds."