export const HERO_TEXT = {
  badge: "Introducing Detect AI",
  titleStart: "Detect your text",
  titleEnd: "in Seconds!",
  description: "Provide your text, and our model will predict its classification. Fast and efficient predictions in seconds.",
  cta: "Get started!"
}

export const VISUALIZER_TEXT = "This text is being analyzed by our advanced AI detection algorithm to determine if it was written by a human or generated by AI. Our model processes patterns, structures, and linguistic features to provide accurate classification in seconds."

export const REVIEWS_DATA = [
  {
    name: "Michael",
    username: "@michael",
    body: "Detect AI is fast and accurate. I use it every day!",
    img: "https://avatar.vercel.sh/michael",
  },
  {
    name: "Sophia",
    username: "@sophia",
    body: "I tested many AI detection tools, but this one actually works.",
    img: "https://avatar.vercel.sh/sophia",
  },
  {
    name: "David",
    username: "@david",
    body: "Super useful! It makes checking AI-generated text effortless.",
    img: "https://avatar.vercel.sh/david",
  },
  {
    name: "Emily",
    username: "@emily",
    body: "This tool is a lifesaver for my work. It helps me spot AI-generated content instantly.",
    img: "https://avatar.vercel.sh/emily",
  },
  {
    name: "Alex",
    username: "@alex",
    body: "It's incredibly accurate and fast, making AI detection easier than ever!",
    img: "https://avatar.vercel.sh/alex",
  },
  {
    name: "Olivia",
    username: "@olivia",
    body: "Simple, reliable, and surprisingly effective. I highly recommend it!",
    img: "https://avatar.vercel.sh/olivia",
  },
]

export const PRICING_PLANS = [
  {
    id: "spark",
    name: "Spark",
    description: "Perfect for individuals getting started with AI detection.",
    price: { monthly: "₹0", yearly: "₹0" },
    features: [
      "Standard AI detection",
      "100 scans per day",
      "Basic reporting",
      "Community support"
    ],
    popular: false,
    cta: "Get Started"
  },
  {
    id: "flare",
    name: "Flare",
    description: "Advanced power for professionals and heavy users.",
    price: { monthly: "₹200", yearly: "₹1000" },
    features: [
      "Advanced AI detection",
      "Unlimited scans",
      "Deep analysis & insights",
      "Priority support",
      "Early access to features"
    ],
    popular: true,
    cta: "Upgrade Now"
  }
]

export const FAQS_LIST = [
  {
    question: "What is Detect AI?",
    answer: "Detect AI is a tool that helps identify whether a piece of text is AI-generated or human-written.",
  },
  {
    question: "How accurate is Detect AI?",
    answer: "Detect AI uses advanced models like SNN and BERT to ensure high accuracy in AI text detection.",
  },
  {
    question: "Is Detect AI free to use?",
    answer:
      "Yes! We offer a free plan with basic detection features, while the premium plan provides advanced analysis.",
  },
  {
    question: "Can Detect AI detect mixed AI and human-written content?",
    answer: "Yes, it can analyze hybrid content and highlight AI-generated sections.",
  },
  {
    question: "Do I need an account to use Detect AI?",
    answer:
      "No, you can use the free version without an account. However, creating an account unlocks additional features.",
  },
  {
    question: "How does Detect AI handle user data?",
    answer: "We prioritize privacy and do not store or share any text submitted for analysis.",
  },
]