{{- if .Values.monitoring.loki.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-loki
  namespace: {{ .Release.Namespace }}
  labels:
    app: loki
spec:
  serviceName: {{ .Release.Name }}-loki
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
        - name: loki
          image: "grafana/loki:2.9.2"
          imagePullPolicy: IfNotPresent
          args:
            - "-config.file=/etc/loki/local-config.yaml"
          ports:
            - name: http
              containerPort: 3100
              protocol: TCP
          resources:
            limits:
              cpu: "1.0"
              memory: "2Gi"
            requests:
              cpu: "500m"
              memory: "1Gi"
          volumeMounts:
            - name: loki-data
              mountPath: /loki
  volumeClaimTemplates:
    - metadata:
        name: loki-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: {{ .Values.databases.storageClass | quote }}
        resources:
          requests:
            storage: {{ .Values.monitoring.loki.storageSize }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-loki-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: loki
spec:
  ports:
    - port: 3100
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: loki
{{- end }}
