name: detect_ai_cluster

networks:
  detect_ai_network:
    name: ${detect_ai_network}
    driver: bridge

include:
  - path: ./infra/postgres.yml
  - path: ./infra/redis.yml
  - path: ./infra/redis-cluster.yml
  - path: ./infra/redis-events.yml
  - path: ./infra/rabbitmq-cluster.yml
  
  - path: ../../../services/document-parser/infra/compose.yml
  - path: ../../../services/inference/infra/compose.yml
  - path: ../../../services/inference/infra/compose.prod.yml
  - path: ../../../services/inference/infra/compose.gpu.yml
  - path: ../../../services/workers/compose.yml
  - path: ../../../services/payments/gateway/infra/compose.yml
  - path: ../../../services/payments/gateway/infra/compose.prod.yml
  - path: ../../../services/chats/compose.yml
  
  - path: ../../../apps/web/compose.yml
