networks:
  detectai_net:
    name: detect_ai_network
    external: true

services:
  chat-redis-1:
    image: redis:7.2
    container_name: chat_redis_1
    command: >
      redis-server 
      --port 7010 
      --cluster-enabled yes 
      --cluster-config-file nodes.conf 
      --cluster-node-timeout 5000 
      --appendonly yes 
      --cluster-announce-ip chat_redis_1
      --cluster-announce-port 7010 
      --cluster-announce-bus-port 17010
    ports:
      - "7010:7010"
      - "17010:17010"
    volumes:
      - redis-chat-1-data:/data
    networks:
      - detectai_net

  chat-redis-2:
    image: redis:7.2
    container_name: chat_redis_2
    command: >
      redis-server 
      --port 7011 
      --cluster-enabled yes 
      --cluster-config-file nodes.conf 
      --cluster-node-timeout 5000 
      --appendonly yes 
      --cluster-announce-ip chat_redis_2
      --cluster-announce-port 7011 
      --cluster-announce-bus-port 17011
    ports:
      - "7011:7011"
      - "17011:17011"
    volumes:
      - redis-chat-2-data:/data
    networks:
      - detectai_net

  chat-redis-3:
    image: redis:7.2
    container_name: chat_redis_3
    command: >
      redis-server 
      --port 7012 
      --cluster-enabled yes 
      --cluster-config-file nodes.conf 
      --cluster-node-timeout 5000 
      --appendonly yes 
      --cluster-announce-ip chat_redis_3
      --cluster-announce-port 7012 
      --cluster-announce-bus-port 17012
    ports:
      - "7012:7012"
      - "17012:17012"
    volumes:
      - redis-chat-3-data:/data
    networks:
      - detectai_net

  chat-cluster-initiator:
    image: redis:7.2
    container_name: chat_redis_init
    depends_on:
      - chat-redis-1
      - chat-redis-2
      - chat-redis-3
    command: >
      bash -c "sleep 5 && 
      redis-cli --cluster create 
      chat_redis_1:7010 
      chat_redis_2:7011 
      chat_redis_3:7012 
      --cluster-replicas 0 --cluster-yes"
    networks:
      - detectai_net

  chat-mongo-config:
    image: mongo:6.0
    container_name: chat_mongo_config
    command: mongod --configsvr --replSet configRS --bind_ip_all --port 27017
    networks:
      - detectai_net
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "rs.initiate({_id: 'configRS', configsvr: true, members: [{_id: 0, host: 'chat_mongo_config:27017'}]})" ]
      interval: 5s
      start_period: 5s

  chat-mongo-shard:
    image: mongo:6.0
    container_name: chat_mongo_shard
    command: mongod --shardsvr --replSet shardRS --bind_ip_all --port 27017
    networks:
      - detectai_net
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "rs.initiate({_id: 'shardRS', members: [{_id: 0, host: 'chat_mongo_shard:27017'}]})" ]
      interval: 5s
      start_period: 5s

  chat-mongo-router:
    image: mongo:6.0
    container_name: chat_mongo_router
    command: mongos --configdb configRS/chat_mongo_config:27017 --bind_ip_all --port 27017
    ports:
      - "27018:27017"
    networks:
      - detectai_net
    depends_on:
      chat-mongo-config:
        condition: service_healthy
      chat-mongo-shard:
        condition: service_healthy

  chat-mongo-init:
    image: mongo:6.0
    container_name: chat_mongo_init
    networks:
      - detectai_net
    depends_on:
      - chat-mongo-router
    command: >
      bash -c "
        sleep 10 &&
        mongosh --host chat_mongo_router:27017 --eval 'sh.addShard(\"shardRS/chat_mongo_shard:27017\"); sh.enableSharding(\"chat_db\"); sh.shardCollection(\"chat_db.messages\", { chat_id: \"hashed\" });'
      "

  chat-service:
    build: .
    container_name: chat_api
    environment:
      - APP_ENV=production
      - SERVICE_ROLE=api
      - GRPC_PORT=:50051
      - METRICS_PORT=:9091
      - MONGO_URI=mongodb://chat_mongo_router:27017
      - MONGO_DATABASE=chat_db
      - REDIS_CLUSTER_ADDRS=chat_redis_1:7010,chat_redis_2:7011,chat_redis_3:7012
      - WORKER_CONCURRENCY=10
      - STREAM_PARTITION_COUNT=16
    ports:
      - "50052:50051"
      - "9095:9091"
    depends_on:
      chat-mongo-init:
        condition: service_started
      chat-cluster-initiator:
        condition: service_started
    networks:
      - detectai_net

  chat-worker:
    build: .
    container_name: chat_worker
    environment:
      - APP_ENV=production
      - SERVICE_ROLE=worker
      - METRICS_PORT=:9099
      - MONGO_URI=mongodb://chat_mongo_router:27017
      - MONGO_DATABASE=chat_db
      - REDIS_CLUSTER_ADDRS=chat_redis_1:7010,chat_redis_2:7011,chat_redis_3:7012
      - BATCH_SIZE=50
      - STREAM_PARTITION_COUNT=16
    ports:
      - "9099:9099"
    depends_on:
      chat-mongo-init:
        condition: service_started
      chat-cluster-initiator:
        condition: service_started
    networks:
      - detectai_net

volumes:
  redis-chat-1-data:
  redis-chat-2-data:
  redis-chat-3-data: