services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: shared_rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - detectai_net

networks:
  detectai_net:
    name: detect_ai_network
    external: true