up-lite:
	docker compose -f docker-compose.lite.yml up -d

up-full:
	docker compose up -d

down-lite:
	docker compose -f docker-compose.lite.yml down

down-full:
	docker compose down

up-build-full: 
	docker compose --build -d 

up-build-lite:
	docker compose -f docker-compose.lite.yml up --build -d
