"""Thin re-export — canonical metrics live in infrastructure."""

from app.infrastructure.executor.extraction_pool import (
    get_pool_stats,
    is_extraction_pool_healthy as is_process_pool_healthy,
    mark_extraction_finished,
    mark_extraction_started,
    refresh_pool_gauges as refresh_process_pool_gauges,
    register_extraction_pool as register_process_pool,
)
from app.infrastructure.observability.metrics import (
    EXTRACTION_COMPRESSION_RATIO,
    EXTRACTION_DURATION_SECONDS,
    EXTRACTION_FAILURES_TOTAL,
    EXTRACTION_POOL_ACTIVE_THREADS,
    EXTRACTION_POOL_MAX_WORKERS,
    EXTRACTION_POOL_QUEUE_DEPTH,
    EXTRACTION_QUEUE_WAIT_SECONDS,
    EXTRACTED_TEXT_BYTES_TOTAL,
    EXTRACTED_TEXT_LENGTH_BYTES,
    EXTRACTION_TIMEOUTS_TOTAL,
    HTTP_REQUEST_DURATION_SECONDS,
    HTTP_REQUEST_ERRORS_TOTAL,
    HTTP_REQUESTS_TOTAL,
    IN_FLIGHT_REQUESTS,
    PARSED_DOCUMENTS_TOTAL,
    PARSED_FILE_SIZE_BYTES,
    REJECTED_UPLOADS_TOTAL,
    classify_extraction_error,
    record_extraction,
    record_extraction_duration,
    record_extraction_failure,
    record_extraction_queue_wait,
    record_extraction_timeout,
    record_rejected_upload,
    record_request,
    render_metrics,
)

__all__ = [
    "HTTP_REQUESTS_TOTAL",
    "HTTP_REQUEST_ERRORS_TOTAL",
    "HTTP_REQUEST_DURATION_SECONDS",
    "PARSED_FILE_SIZE_BYTES",
    "PARSED_DOCUMENTS_TOTAL",
    "EXTRACTED_TEXT_BYTES_TOTAL",
    "EXTRACTION_FAILURES_TOTAL",
    "EXTRACTION_TIMEOUTS_TOTAL",
    "REJECTED_UPLOADS_TOTAL",
    "IN_FLIGHT_REQUESTS",
    "EXTRACTION_QUEUE_WAIT_SECONDS",
    "EXTRACTION_POOL_ACTIVE_THREADS",
    "EXTRACTION_POOL_QUEUE_DEPTH",
    "EXTRACTION_POOL_MAX_WORKERS",
    "EXTRACTION_DURATION_SECONDS",
    "EXTRACTED_TEXT_LENGTH_BYTES",
    "EXTRACTION_COMPRESSION_RATIO",
    "classify_extraction_error",
    "record_extraction",
    "record_extraction_duration",
    "record_extraction_failure",
    "record_extraction_queue_wait",
    "record_extraction_timeout",
    "record_rejected_upload",
    "record_request",
    "render_metrics",
    "get_pool_stats",
    "is_process_pool_healthy",
    "mark_extraction_started",
    "mark_extraction_finished",
    "refresh_process_pool_gauges",
    "register_process_pool",
]
