networks:
  detectai_net:
    external: true

services:
  redis-cluster-node-0:
    image: bitnami/redis-cluster:7.2
    container_name: detect_ai_redis_cluster_0
    restart: unless-stopped
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_NODES=redis-cluster-node-0 redis-cluster-node-1 redis-cluster-node-2
    networks:
      - detectai_net
    healthcheck:
      test: ["CMD", "redis-cli", "-c", "-p", "6379", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis-cluster-node-1:
    image: bitnami/redis-cluster:7.2
    container_name: detect_ai_redis_cluster_1
    restart: unless-stopped
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_NODES=redis-cluster-node-0 redis-cluster-node-1 redis-cluster-node-2
    networks:
      - detectai_net
    healthcheck:
      test: ["CMD", "redis-cli", "-c", "-p", "6379", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis-cluster-node-2:
    image: bitnami/redis-cluster:7.2
    container_name: detect_ai_redis_cluster_2
    restart: unless-stopped
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_NODES=redis-cluster-node-0 redis-cluster-node-1 redis-cluster-node-2
    networks:
      - detectai_net
    healthcheck:
      test: ["CMD", "redis-cli", "-c", "-p", "6379", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5