apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: api
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: api-port
      protocol: TCP
      name: api-port
  selector:
    app: api
    release: {{ .Release.Name }}