apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-chats-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: chats-api
spec:
  type: {{ .Values.chats.api.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.chats.api.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: {{ .Values.chats.api.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app: chats-api
    release: {{ .Release.Name }}
