apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-inference-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: inference
spec:
  type: {{ .Values.inference.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.inference.service.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: {{ .Values.inference.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app: inference
    release: {{ .Release.Name }}
