services:
  worker-analytics:
    container_name: worker_analytics
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    command: ["bun", "run", "start:analytics"]
    env_file: .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_URL_REPLICA=${DATABASE_URL_REPLICA}
      - REDIS_URL=${REDIS_URL}
      - REDIS_USAGE_URL=${REDIS_USAGE_URL}
      - REDIS_MODE=${REDIS_MODE:-standalone}
      - NODE_ENV=production
    networks:
      - detectai_net

  worker-cron:
    container_name: worker_cron
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    command: ["bun", "run", "start:cron"]
    env_file: .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_URL_REPLICA=${DATABASE_URL_REPLICA}
      - REDIS_URL=${REDIS_URL}
      - REDIS_MODE=${REDIS_MODE:-standalone}
      - NODE_ENV=production
    networks:
      - detectai_net

  worker-payments:
    container_name: worker_payments
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    command: ["bun", "run", "start:payments"]
    ports:
      - "7777:7777"
    env_file: .env
    environment:
      - RABBITMQ_URL=${RABBITMQ_URL}
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_URL_REPLICA=${DATABASE_URL_REPLICA}
      - REDIS_URL=${REDIS_URL}
      - REDIS_MODE=${REDIS_MODE:-standalone}
      - PADDLE_API_KEY=${PADDLE_API_KEY}
      - PADDLE_ENVIRONMENT=${PADDLE_ENVIRONMENT:-sandbox}
      - NODE_ENV=production
    networks:
      - detectai_net

networks:
  detectai_net:
    name: detect_ai_network
    external: true