networks:
  detectai_net:
    name: detect_ai_network
    external: true

services:
  document-parser:
    container_name: document_parser
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5001:8000"
    networks:
      - detectai_net
    env_file:
      - .env