networks:
  detectai_net:
    name: detect_ai_network
    external: true

services:
  payment-gateway:
    container_name: payment_gateway
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - detectai_net