networks:
  detectai_net:
    name: detect_ai_network
    external: true

services:
  payment-gateway:
    container_name: payment_gateway
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    environment:
      - RABBITMQ_URL=amqp://guest:guest@shared_rabbitmq:5672/
      - PORT=8080
    env_file:
      - .env
    depends_on:
      - rabbitmq
    networks:
      - detectai_net