import { createEnv } from "@t3-oss/env-nextjs"
import { z } from "zod"

export const env = createEnv({
  server: {
    DATABASE_URL: z.string().url(),
    DATABASE_URL_REPLICA: z.string().url().optional(),
    NEXTAUTH_SECRET: z.string().min(1),
    NEXTAUTH_URL: z.string().url().optional(),
    NODE_ENV: z.enum(["development", "test", "production"]).default("development"),
    LOG_LEVEL: z.enum(["debug", "info", "warn", "error"]).default("info"),
    GOOGLE_ID: z.string().min(1),
    GOOGLE_SECRET: z.string().min(1),
    GITHUB_ID: z.string().min(1),
    GITHUB_SECRET: z.string().min(1),
    TURNSTILE_SECRET_KEY: z.string().min(1),
    REDIS_MODE: z.enum(["standalone", "sentinel"]).default("sentinel"),
    REDIS_URL: z.string().url().optional(),
    REDIS_SENTINELS: z.string().min(1).default("localhost:26379,localhost:26380,localhost:26381"),
    REDIS_MASTER_NAME: z.string().min(1).default("mymaster"),
    REDIS_PASSWORD: z.string().optional(),
    REDIS_USAGE_MODE: z.enum(["standalone", "cluster"]).optional(),
    REDIS_USAGE_PASSWORD: z.string().optional(),
    REDIS_USAGE_URL: z.string().min(1),
    USE_REDIS_CLUSTER: z.string().transform((s) => s === "true").pipe(z.boolean()).optional(),
    FILE_EXTRACTOR_API_URL: z.string().url(),
    AI_SERVICE_URL: z.string().min(1),
    AI_SERVICE_API_KEY: z.string().min(1),
    CHAT_SERVICE_URL: z.string().min(1).default("localhost:50051"),
    PAYMENT_GATEWAY_URL: z.string().url().default("http://payment-gateway:8080"),
    INTERNAL_API_KEY: z.string().optional(),
    PROMETHEUS_WEB_SCRAPE_TOKEN: z.string().min(1).optional(),
  },
  client: {
    NEXT_PUBLIC_TURNSTILE_SITE_KEY: z.string().min(1),
    NEXT_PUBLIC_PADDLE_CLIENT_TOKEN: z.string().min(1),
  },
  runtimeEnv: {
    DATABASE_URL: process.env.DATABASE_URL,
    DATABASE_URL_REPLICA: process.env.DATABASE_URL_REPLICA,
    NEXTAUTH_SECRET: process.env.NEXTAUTH_SECRET,
    NEXTAUTH_URL: process.env.NEXTAUTH_URL,
    NODE_ENV: process.env.NODE_ENV,
    LOG_LEVEL: process.env.LOG_LEVEL,
    GOOGLE_ID: process.env.GOOGLE_ID,
    GOOGLE_SECRET: process.env.GOOGLE_SECRET,
    GITHUB_ID: process.env.GITHUB_ID,
    GITHUB_SECRET: process.env.GITHUB_SECRET,
    TURNSTILE_SECRET_KEY: process.env.TURNSTILE_SECRET_KEY,
    REDIS_MODE: process.env.REDIS_MODE,
    REDIS_URL: process.env.REDIS_URL,
    REDIS_SENTINELS: process.env.REDIS_SENTINELS,
    REDIS_MASTER_NAME: process.env.REDIS_MASTER_NAME,
    REDIS_PASSWORD: process.env.REDIS_PASSWORD,
    REDIS_USAGE_MODE: process.env.REDIS_USAGE_MODE,
    REDIS_USAGE_PASSWORD: process.env.REDIS_USAGE_PASSWORD,
    FILE_EXTRACTOR_API_URL: process.env.FILE_EXTRACTOR_API_URL,
    REDIS_USAGE_URL: process.env.REDIS_USAGE_URL,
    USE_REDIS_CLUSTER: process.env.USE_REDIS_CLUSTER, 
    NEXT_PUBLIC_TURNSTILE_SITE_KEY: process.env.NEXT_PUBLIC_TURNSTILE_SITE_KEY,
    NEXT_PUBLIC_PADDLE_CLIENT_TOKEN: process.env.NEXT_PUBLIC_PADDLE_CLIENT_TOKEN,
    AI_SERVICE_URL: process.env.AI_SERVICE_URL,
    AI_SERVICE_API_KEY: process.env.AI_SERVICE_API_KEY,
    CHAT_SERVICE_URL: process.env.CHAT_SERVICE_URL,
    PAYMENT_GATEWAY_URL: process.env.PAYMENT_GATEWAY_URL,
    INTERNAL_API_KEY: process.env.INTERNAL_API_KEY,
    PROMETHEUS_WEB_SCRAPE_TOKEN: process.env.PROMETHEUS_WEB_SCRAPE_TOKEN,
  },
  skipValidation: !!process.env.SKIP_ENV_VALIDATION,
  emptyStringAsUndefined: true,
})
